# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-18 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20161018_1642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.IntegerField(),
        ),
    ]
