# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-17 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_auto_20161017_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods',
            name='sell_until',
            field=models.DateTimeField(null=True),
        ),
    ]
