# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 08:20
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0011_order_uuid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['display_order'], 'verbose_name': '카테고리', 'verbose_name_plural': '카테고리'},
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['display_order'], 'verbose_name': '상품', 'verbose_name_plural': '상품'},
        ),
        migrations.AddField(
            model_name='category',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='카테고리 순서(작은게 먼저)'),
        ),
        migrations.AddField(
            model_name='goods',
            name='display_order',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='카테고리 내 순서(작은게 먼저)'),
        ),
        migrations.AddField(
            model_name='goods',
            name='stock',
            field=models.PositiveIntegerField(default=1000, verbose_name='재고'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='goods.Category', verbose_name='카테고리'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='description',
            field=ckeditor.fields.RichTextField(verbose_name='상품설명'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='판매중'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='name',
            field=models.CharField(max_length=200, verbose_name='상품명'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='가격(달러)'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='sell_until',
            field=models.DateField(blank=True, null=True, verbose_name='판매종료일'),
        ),
    ]
