# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 09:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0012_auto_20170907_1720'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='goods',
            name='stock',
        ),
        migrations.AddField(
            model_name='goods',
            name='max_stock',
            field=models.PositiveIntegerField(default=1000, verbose_name='판매 재고(전체)'),
        ),
    ]
