# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-07 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0013_auto_20170907_1846'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='goods',
            options={'ordering': ['category', 'display_order'], 'verbose_name': '상품', 'verbose_name_plural': '상품'},
        ),
    ]
