# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 07:36
from __future__ import unicode_literals

import address.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0014_auto_20170907_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('b', '계좌이체'), ('p', 'Paypal')], default='b', max_length=1, verbose_name='결제수단'),
        ),
        migrations.AddField(
            model_name='order',
            name='usd_to_krw',
            field=models.IntegerField(blank=True, default=0, verbose_name='환율'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='additional_address',
            field=models.TextField(blank=True, null=True, verbose_name='상세주소'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=address.models.AddressField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='address.Address', verbose_name='주소'),
        ),
        migrations.AlterField(
            model_name='order',
            name='custom_order',
            field=models.TextField(blank=True, null=True, verbose_name='주문요청건'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ingress_agent_name',
            field=models.CharField(max_length=200, verbose_name='Ingress Agent Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='ingress_mail',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Ingress 메일주소'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='결제완료'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_shipping',
            field=models.BooleanField(default=False, verbose_name='배송건'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='주문고객'),
        ),
    ]
