# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 07:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0015_auto_20170912_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bank_transfer_name',
            field=models.CharField(blank=True, max_length=20, verbose_name='계좌이체 표시이름'),
        ),
    ]
