# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-12 08:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0016_order_bank_transfer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bank_transfer_name',
            field=models.CharField(default='', max_length=20, verbose_name='계좌이체 표시이름'),
        ),
        migrations.AlterField(
            model_name='order',
            name='usd_to_krw',
            field=models.IntegerField(default=0, verbose_name='환율'),
        ),
    ]
